# Generated by Django 5.0.4 on 2025-09-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cls_Modularten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_art', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cls_Modul_Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_subraumenergieoffset', models.IntegerField(default=0)),
                ('m_energieverbrauch', models.IntegerField(default=0)),
                ('m_energieproduktion', models.IntegerField(default=0)),
                ('m_energieproduktionfaktor', models.FloatField(default=0)),
                ('m_warpbonusabsolut', models.IntegerField(default=0)),
                ('m_warpbonusfaktor', models.FloatField(default=0)),
                ('m_initiative', models.IntegerField(default=0)),
                ('m_initiativebonusfaktor', models.FloatField(default=0)),
                ('m_angriffswert', models.IntegerField(default=0)),
                ('m_angriffswertbonusfaktor', models.FloatField(default=0)),
                ('m_schadenswert', models.IntegerField(default=0)),
                ('m_schadenswertbonusfaktor', models.FloatField(default=0)),
                ('m_ruestungsklasseabsolut', models.IntegerField(default=0)),
                ('m_ruestungsklassebonusfaktor', models.FloatField(default=0)),
                ('m_scannerwert', models.IntegerField(default=0)),
                ('m_scannerwertbonusfaktor', models.FloatField(default=0)),
                ('m_scannerreichweite', models.PositiveIntegerField(default=0)),
                ('m_scannerreichweitebonusfaktor', models.FloatField(default=0)),
                ('m_versorgungsgueterkosten', models.PositiveIntegerField(default=0)),
                ('m_tarnungswert', models.IntegerField(default=0)),
                ('m_tarnungswertbonusfaktor', models.FloatField(default=0)),
                ('m_alphawert', models.FloatField(default=1)),
                ('m_betawert', models.FloatField(default=1)),
                ('m_gammawert', models.FloatField(default=1)),
                ('m_technologieart', models.IntegerField(default=0)),
                ('m_modul_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.cls_modularten')),
            ],
        ),
        migrations.CreateModel(
            name='cls_Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_energie', models.IntegerField(default=100)),
                ('m_deathcount', models.IntegerField(default=0)),
                ('m_abschaltpriro', models.IntegerField(default=0)),
                ('m_aktiv', models.BooleanField(default=True)),
                ('m_versorgt', models.BooleanField(default=False)),
                ('m_akt_initiative', models.IntegerField(default=0)),
                ('m_akt_schaden', models.IntegerField(default=0)),
                ('m_akt_angriffswert', models.IntegerField(default=0)),
                ('m_modul_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.cls_modul_library')),
            ],
        ),
    ]
