# Generated by Django 5.0.4 on 2025-09-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cls_module',
            name='m_akt_angriffswert',
        ),
        migrations.RemoveField(
            model_name='cls_module',
            name='m_akt_initiative',
        ),
        migrations.RemoveField(
            model_name='cls_module',
            name='m_akt_schaden',
        ),
        migrations.AddField(
            model_name='cls_modul_library',
            name='m_schildbonusfaktor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cls_modul_library',
            name='m_schildwert',
            field=models.IntegerField(default=0),
        ),
    ]
