# Generated by Django 5.0.4 on 2025-09-02 17:11

import django.db.models.deletion
import schiffe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imperium', '0001_initial'),
        ('karte', '0001_initial'),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cls_schiffskategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_value', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='cls_schiffsklassen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_hitpoint', models.IntegerField()),
                ('m_konsolenanzahl', models.IntegerField()),
                ('m_torpedoanzahl', models.IntegerField()),
                ('m_strahlenwaffenanzahl', models.IntegerField()),
                ('m_maxwarp', models.IntegerField(default=1)),
                ('m_basisruestungsklasse', models.IntegerField(default=10)),
                ('m_schiffskategorie', models.ForeignKey(blank=True, default=schiffe.models.cls_schiffskategorie.get_default_pk, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Kategorie', to='schiffe.cls_schiffskategorie')),
            ],
        ),
        migrations.CreateModel(
            name='cls_schiffe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_imgname', models.CharField(max_length=100)),
                ('m_sollPos', models.CharField(blank=True, max_length=250, null=True)),
                ('m_versorgungsgueter', models.PositiveIntegerField(default=0)),
                ('m_akt_warp', models.PositiveIntegerField(default=0)),
                ('m_akt_hitpoints', models.IntegerField(default=0)),
                ('m_akt_schilde', models.IntegerField(default=0)),
                ('m_akt_ruestungsklasse', models.PositiveIntegerField(default=0)),
                ('m_getarnt', models.BooleanField(default=False)),
                ('m_tarnart', models.IntegerField(default=0)),
                ('m_akt_tarnstufe_alpha', models.IntegerField(default=0)),
                ('m_akt_tarnstufe_beta', models.IntegerField(default=0)),
                ('m_akt_tarnstufe_gamma', models.IntegerField(default=0)),
                ('m_akt_sensorenwert_alpha', models.FloatField(default=0)),
                ('m_akt_sensorenwert_beta', models.FloatField(default=0)),
                ('m_akt_sensorenwert_gamma', models.FloatField(default=0)),
                ('m_akt_reichweite', models.IntegerField(default=0)),
                ('m_deflektor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deflektor', to='module.cls_module')),
                ('m_imperium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Imperium', to='imperium.cls_imperium')),
                ('m_impulsantrieb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impulsantrieb', to='module.cls_module')),
                ('m_istPos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istPos', to='karte.cls_sektor')),
                ('m_konsole', models.ManyToManyField(related_name='m_konsole', to='module.cls_module')),
                ('m_rasse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rasse', to='imperium.cls_rassen')),
                ('m_schilde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schilde', to='module.cls_module')),
                ('m_strahlenwaffen', models.ManyToManyField(related_name='m_strahlenwaffen', to='module.cls_module')),
                ('m_torpedo', models.ManyToManyField(related_name='m_torpedo', to='module.cls_module')),
                ('m_warpkern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warpkern', to='module.cls_module')),
                ('m_klasse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Klasse', to='schiffe.cls_schiffsklassen')),
            ],
        ),
    ]
