# Generated by Django 5.0.4 on 2025-09-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_remove_cls_module_m_akt_angriffswert_and_more'),
        ('schiffe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cls_flotte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cls_schiffe',
            name='m_sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor', to='module.cls_module'),
        ),
        migrations.AddField(
            model_name='cls_schiffe',
            name='m_flotte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Flotte', to='schiffe.cls_flotte'),
        ),
    ]
