# Generated by Django 5.0.4 on 2025-09-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cls_sektorobjekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_art', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cls_sektor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_x', models.PositiveIntegerField()),
                ('m_y', models.PositiveIntegerField()),
                ('m_subraumenergielevel', models.PositiveIntegerField(default=0)),
                ('m_cx', models.IntegerField(default=0)),
                ('m_cy', models.IntegerField(default=0)),
                ('m_cz', models.IntegerField(default=0)),
                ('m_sektorobjekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='karte.cls_sektorobjekt')),
            ],
        ),
    ]
