# Generated by Django 5.0.4 on 2025-09-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cls_rassen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cls_imperium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_rasse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rasse', to='imperium.cls_rassen')),
            ],
        ),
        migrations.CreateModel(
            name='cls_diplomatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FR', 'Frieden'), ('KR', 'Krieg'), ('BU', 'Bündnis'), ('HA', 'Handelsabkommen'), ('NA', 'Nichtangriffspakt'), ('NE', 'Neutralität')], default='NE', max_length=2)),
                ('m_imperium_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imperium_1', to='imperium.cls_imperium')),
                ('m_imperium_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imperium_2', to='imperium.cls_imperium')),
            ],
            options={
                'unique_together': {('m_imperium_1', 'm_imperium_2')},
            },
        ),
    ]
