# Generated by Django 5.0.4 on 2025-09-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imperium', '0001_initial'),
        ('karte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cls_ImperiumScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_alpha_wert', models.SmallIntegerField(default=0)),
                ('m_beta_wert', models.SmallIntegerField(default=0)),
                ('m_gamma_wert', models.SmallIntegerField(default=0)),
                ('m_imperium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imperium', to='imperium.cls_imperium')),
                ('m_sektor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sektor', to='karte.cls_sektor')),
            ],
        ),
    ]
