# Generated by Django 5.0.4 on 2025-09-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imperium', '0001_initial'),
        ('karte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cls_planetenklasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_klasse', models.CharField(max_length=2, unique=True)),
                ('m_typ', models.CharField(max_length=50)),
                ('m_frequenz', models.PositiveIntegerField(help_text='Häufigkeit in Prozent')),
                ('m_titan', models.BooleanField(default=False)),
                ('m_deuterium', models.BooleanField(default=False)),
                ('m_duranium', models.BooleanField(default=False)),
                ('m_kristall', models.BooleanField(default=False)),
                ('m_iridium', models.BooleanField(default=False)),
                ('m_dilithium', models.BooleanField(default=False)),
                ('m_bewohnbarkeit', models.CharField(max_length=50)),
                ('m_beschreibung', models.TextField()),
            ],
            options={
                'verbose_name': 'Planetenklasse',
                'verbose_name_plural': 'Planetenklassen',
                'ordering': ['m_klasse'],
            },
        ),
        migrations.CreateModel(
            name='cls_planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_position', models.PositiveIntegerField(default=0)),
                ('m_name', models.CharField(max_length=100)),
                ('m_bevoelkerung', models.PositiveIntegerField(default=0)),
                ('m_anbauzone', models.PositiveIntegerField(default=0)),
                ('m_besitzer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imperium.cls_imperium')),
                ('m_sektor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karte.cls_sektor')),
                ('m_klasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planet.cls_planetenklasse')),
            ],
        ),
    ]
