# Generated by Django 5.0.4 on 2025-09-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imperium', '0002_cls_imperiumscan'),
        ('planet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cls_planet',
            name='m_heimatplanet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cls_planet',
            name='m_besitzer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imperium.cls_imperium'),
        ),
    ]
